/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMacro */

#ifndef _Included_NativeMacro
#define _Included_NativeMacro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMacro
 * Method:    leftClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_leftClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    leftDoubleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_leftDoubleClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    rightClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_rightClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    middleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_middleClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    typeChar
 * Signature: (CII)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_typeChar
  (JNIEnv *, jobject, jchar, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    typeEscape
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_typeEscape
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMacro
 * Method:    scrollDown
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_NativeMacro_scrollDown
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
